version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/maoni-sample"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/maoni-common"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/maoni"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/callbacks/maoni-doorbell"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/callbacks/maoni-email"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/callbacks/maoni-github"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/callbacks/maoni-jira"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"

  - package_manager: "java:gradle"
    directory: "/callbacks/maoni-slack"
    update_schedule: "weekly"
    default_reviewers:
      - "rm3l"
    default_labels:
      - "dependencies"
